Merging from upstream (#26). This updates to INL@7cd7660
* Changes to provide an instrumentation package to allow for metrics gathering

* Bump log4j-core from 2.13.3 to 2.15.0

Bumps log4j-core from 2.13.3 to 2.15.0.

---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Adds configuration to control response of Hits and GropuedHits

* Addressing code review comments

* Be extra defensive about when to exclude context.

* RequestHandlerHits and -HitsGrouped now share a writeHits method.

This gets rid of some duplicate code.

* Document config changes.

* Bump log4j-core from 2.15.0 to 2.16.0

Bumps log4j-core from 2.15.0 to 2.16.0.

---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Document new includegroupcontents parameter.

* Clarify documentation and error message for forEachPath on subAnnotation

Previously a somewhat cryptic error would be generated containing the valuePath as annotion name e.g. 11:32:24.829 [pool-3-thread-1] ERROR nl.inl.blacklab.index.DocIndexer - (...)\ONW-processed-metadata-v3\leys_1957.xml: skipping undeclared annotation ./@name
Now just output a proper warning containing the actual undeclared annotation

* Fix viewing single group in grouped hits.

* Add v2.2.1 details, log4j fix to changelog.

* Update changelog.md with latest changes.

* Bump log4j-core from 2.16.0 to 2.17.1

Bumps log4j-core from 2.16.0 to 2.17.1.

---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Provides an implementation of metrics provider via prometheus

* Adds an prometheus implementation to MetricsProvider, wires in system metrics

* Use maven.compiler.source/target.

* Add README.md and test/ dir to instrumentation.

* Changes index cleanup to async via file system listening

* makes fs polling freq  into a variable

* Closes index after removal

Closes index after removal

* add a null check to prevent an Exception

* Code style.

* Remove searches before closing index (thanks @tcbrouwer!).

* Fixes index repetition in metadata creation

* Fix cross compilation bugs by also specifying maven compile release

See https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

* Implements workaround when metadata contains newlines and colons

* Documentation, e.g. described list of modules.

* Make it explicit when we need stored hits when grouping.

* HitGroupsTokenFrequencies.canUse() decides whether it can be used.

* Comments, README files.

* Fix incorrect access modifiers.

* Fixes NullPointerException when getting Index from Reader

* Remove BlackLab.createEngine() without params. Comment.

* Document packages using package-info.java.

* Update links to reflect branch rename.

* Update version to 2.2.0.

* Updated version to 2.3.0-SNAPSHOT.

* Remove interfaces dependecy from engine module.

* Remove empty module 'interfaces'.

* Set language level to Java 9. Eliminate ArrayUtil.

* Update changelog.

* Remove support for obsolete content store formats.

* Remove support for obsolete FI file formats.

* Remove unused checkAgainMs.

* Remove deprecated Indexer.isClosed().

* Remove deprecated methods from Indexer, IndexerImpl.

* Remove deprecated methods from BlackLabIndex(Impl/Writer).

* Remove deprecated methods from DocResults, TextPattern.

* Alternative cache implementation (by @eginez).

Adds an alternative cache implementation for smaller/ephemeral indices.

Squashed commit of the following:

commit b2f3d12f21feab1fef22fcbbcc64625ebe1159b5
Author: Jan Niestadt <jan.niestadt@ivdnt.org>
Date:   Thu Feb 10 11:24:00 2022 +0100

    Remove the need for CacheInfoDataStream.

commit 25fbc2b7ef04cfc3d7883527987b6a97d6a747b8
Author: Jan Niestadt <jan.niestadt@ivdnt.org>
Date:   Thu Feb 10 10:47:34 2022 +0100

    Eliminate old constructor for BlsCache.

commit 52af0169b5cdacb10791e995aad1ff272e8a74e0
Author: Jan Niestadt <jan.niestadt@ivdnt.org>
Date:   Thu Feb 10 10:46:28 2022 +0100

    Instantiate BlsCache by class as well.

commit b5f58f8ab1d2cb06c8b33a09babcc2b76ddd1c50
Author: Esteban Ginez <175813+eginez@users.noreply.github.com>
Date:   Wed Feb 9 08:31:16 2022 -0800

    Adds an alternative cache implementation for smaller indices

* Remove SQLite logging. (#254)

* Remove old terminology, update comments and changelog (#255)

* Clarified deprecation warning in Hits.
* Comment fix.
* Correctly use 'annotation' instead of old term '(token) property'.
* Correctly use 'annotated field' instead of old term 'complex field'.
* Update changelog.

* Only load document fields we actually need (#256)

* Don't load Document fields we don't need.

* Add test for fast path hit grouping (HitGroupsTokenFrequencies).

* Add test case for grouping hits filtered by metadata.

* Add GitHub action to build/test on push and PR

* Remove old Travis CI file (no longer used).

* Fix BlsCache after incorrect merge.

* Added to blacklab-internals.md.

* test: use waitfortotal=true, usecache=no.

* Gracefully shut down ExecutorServices.

BlackLab applications that only run very briefly would still be opening the
forward index in the initializationExecutorService when shutdownNow() was
called, resulting in error messages. Now we shut down the ExecutorServices
more gracefully.

Applications that don't close their indexes also hang because there's still
background threads running, but that's on them.

* Catch Exception.

* If indexer didn't find docs or tokens in a file, warn about it.

This check was broken since introducing multithreaded indexing,
but should now work again.

Also set the default log level to warn for IndexTool so the warnings
actually show up in the console.

Fixes #125.

* Fixed intermittent crashes using synchronization. (#259)

There would occassionaly be strange crashes while searching, mostly related to reading
from the Lucene index or the forward index.

An example of a query that frequently crashed, especially shortly after starting the server:

/test/hits?patt=%5B%5D&sort=wordleft%3Aword%3Ai%2Cwordright%3Aword%3Ai%2Cfield%3Apid&wordsaroundhit=1
(usecache=no, waitfortotal=true were also passed)

The problems appear to have been introduced when some operations were parallelized, but because
classes weren't clearly marked as threadsafe or not, not all necessary synchronization was done.

This adds synchronization where needed and marks several important classes as
thread-safe (or not). This appears to solve the intermittent crashes.

It would be good to investigate and document the thread-safety of more classes.

* Remove unused variable.

* Fix off by one in DocResults. Document extra closing token. (#261)

Document length in Lucene and forward index is always reported as one higher due to punctuation being a trailing value. We call this the "extra closing token".

The code wasn't always explicit about what document length meant; sometimes it included the extra closing token, sometimes not. I've tried to document it so it's clear which value we're dealing with.

Also discovered an off-by-one bug in DocResults because we forgot to subtract the extra closing token.

* New GitHub Action to run integration tests (#262)

Adds a test/run.sh script and a GitHub Actions workflow integration-test.yml that runs it on push / PR to dev.

* Clarify forward index matching a bit. (#263)

* Fix and simplify how results are counted, allow peeking during count (#260)

Fixes long counts getting stuck.

Removes the separate job that gathers all hits in favour of having just a count job that does that, and allowing peeking while the count job is running.

* Don't disable cache for testing as this causes issues.

See #266.

* Fix and simplify peeking at count. (#267)

Before we used a delegate, but this created problems when other
parts of the code assumed all hits had been gathered, so therefore
the count obtained via another search would be the final count right
away, but because executeInternal handn't been called yet on the
SearchCountFromResults operation, the delegate returned 0 instead
of the final count.

The other parts of the code that make assumptions about related searches
should also be improved to be more explicit about how searches relate
to one another, and what the state of each search is (running, completed, etc.).

* Commented about cleanup in HitsFromQueryParallel.

* BlackLab internals: more about FI and optimizations.

* Ensure all BLSpans are startpoint-sorted. (#268)

If this is not the case, BLSpans.advanceStartPosition cannot work correctly.
This may have lead to missing certain matches in rare cases.

* Make sure count cannot be aborted before first hits are produced.

* Be more specific about how Search objects are created from SearchParameters.

* Reduce log chatter, clean up unused methods.

* Change error message to be more technical.

Previous message could be interpreted as somehow being the user's
fault, which we want to avoid.

* Allow toggling of BlockTimer logging.

* Some more optimizations for hit frequencies (#270)

* Fix pom.xml errors.

* fixing tests

* Only warn about metadata value being too long once.

* Fix: Hits.get() should ensure hits is available.

* Passes a future task to searches yeilding count as results. The future task should represent the actual search results that need counting

* Passes a future task to searches yeilding count as results. The future task should represent the actual search results that need counting (#275)

* Peek without waiting. Immutable Search classes.

* Slight tweaks.

* Remove the need to wait short time for future.

* Make it possible to monitor running count again.

* Null checks. Final peekValue.

* Various fixes to ResultsCache (#277)

* ResultsStatsDelegate still produces final count even without progressReporter.

* Peek without waiting. Immutable Search classes. (#276)

SearchResultsFromCount is now immutable again, as all Search classes should be.

Instead, to be able to follow the running hits/docs count, we now pass a Peekable (implemented by SearchCacheEntry) to executeInternal(). This method can use the object returned by Peekable.peek() to give updates on its progress while the search is executing. If null is passed to executeInternal(), you won't be able to follow the running count, but everything should work correctly otherwise.

For counting, because we want to be able return a ResultsStats object right away, even if the "real" count isn't available yet, we use ResultsStatsDelegate. This will return 0 if the real count isn't available and delegate to the real count object when it is. CAUTION: if you call processedTotal() or countedTotal() on the ResultsStatsDelegate, it will need to block until all hits have been processed. All other operations will return right away, however.

This has gotten fairly complex and it would be nice to simplify this in the future, while preserving functionality.

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Jan Niestadt <jan.niestadt@ivdnt.org>
Co-authored-by: KCMertens <koen.mmm@gmail.com>
Co-authored-by: Koen Mertens <koen.mertens@ivdnt.org>
Co-authored-by: Tim Brouwer <Tim.Brouwer@ivdnt.org>